### ISSUE TITLE
ocvWrapper  dll hard coded problem

### ISSUE THREAD

**Issue by hafedh-trimeche** [gidesa/ocvWrapper24#1]
Hello,

Please note that under the Debug mode, the DLL path is set to:
`ocvWrapper = 'D:\GDS\progC\ocvWrapper\bin\Debug\x86\ocvCPPWrapper24.dll';
`
It would be better to set it as a relative path with the **delayed** load option.

Best regards.

**Comment by gidesa** [comment]
Hello,
thank you for your comment and suggestions.
I have modified OPENCVWrapper.pas. 
So now it simply load the DLL whenever it find, also in DEBUG mode. 
When we want to debug the DLL, need to define the DEBUGDLL symbol. The precise directory for debugging DLL is encapsulated in an external .inc file,  included only when DEBUGDLL is defined. 
The reason to have a specific debugging directory: when debugging the DLL with Visual C++ debugger, the Delphi program is used as the host application, but it must load the exact DLL under debug, not a generic DLL with that name.

About using "delayed", it's an interesting idea. Although it's not supported by Freepascal, so it would be quite cumbersome to have a bunch of $IFDEF FPC on every external function definitions.
Maybe in future releases I will manage it.
